config/routes.rb
Depot::Application.routes.draw do

  get "admin" => 'admin#index'
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

    resources :users

    resources :orders

    resources :line_items

    resources :carts

    get "store/index"

    resources :products do
      get :who_bought, on: :member
    end
  
    root to: 'store#index', as: 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokemonオンラインストア</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller.controller_name %>">
	<div id="banner" style="font-family: Lucida Grande, Geneva, Verdana, Arial">
		<img src="images/mona.jpg" width="40px" height="60px">
		<%= @page_title || "Pokemon card store" %>
	</div>
	<div id="columns">
		<div id="side">
		<% if @cart %>
			<%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
				<%= render @cart %>
			<% end %>
		<% end %>
			
			<ul style="margin-top: 50px;line-height: 200%">
				<li><a href="/">ホーム</a></li>
				<li><a href="http://www...">よくある質問</a></li>
				<li><a href="http://www...">ニュース</a></li>
				<li><a href="http://www...">お問い合わせ</a></li>
			</ul>
			
			<% if session[:user_id] %>
				<ul>
					<li><%= link_to '注文', orders_path %></li>
					<li><%= link_to '商品', products_path %></li>
					<li><%= link_to 'ユーザー', users_path %></li>
				</ul>
				<%= button_to 'ログアウト', logout_path, method: :delete %>
			<% end %>
		</div>
		<div id="main">
			<%= yield %>			
		</div>
	</div>
</body>
</html>